const mongoose = require('mongoose')

const Schema = mongoose.Schema;


const GenreSchema = new Schema({
  name: {type: String, required: true, maxLength: 100}
})


// Virtual for bookinstance's URL
GenreSchema.virtual('url').get(function () { //  Defines a getter function for the url virtual property. When you access author.url, this function will be executed to return the computed value.
  // We don't use an arrow function as we'll need the this object
  return `/catalog/genre/${this._id}`;  // returns a URL string that includes the _id of the author. The _id is a unique identifier automatically generated by MongoDB for each document.
}) 



// Export model
module.exports = mongoose.model('Genre', GenreSchema);



/*
The model should have a String SchemaType called name to describe the genre.
This name should be required and have between 3 and 100 characters.
Declare a virtual for the genre's URL, named url.
Export the model.
*/